//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCalculator {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText calc_result;
		
		protected System.Web.UI.WebControls.Button Button7;
		
		protected System.Web.UI.WebControls.Button Button8;
		
		protected System.Web.UI.WebControls.Button Button9;
		
		protected System.Web.UI.WebControls.Button ButtonMinus;
		
		protected System.Web.UI.WebControls.Button Button4;
		
		protected System.Web.UI.WebControls.Button Button5;
		
		protected System.Web.UI.WebControls.Button Button6;
		
		protected System.Web.UI.WebControls.Button ButtonMultiply;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected System.Web.UI.WebControls.Button Button3;
		
		protected System.Web.UI.WebControls.Button ButtonDivide;
		
		protected System.Web.UI.WebControls.Button Button0;
		
		protected System.Web.UI.WebControls.Button ButtonBracketsOpen;
		
		protected System.Web.UI.WebControls.Button ButtonBracketsClose;
		
		protected System.Web.UI.WebControls.Button ButtonPlus;
		
		protected System.Web.UI.WebControls.Button ButtenC;
		
		protected System.Web.UI.WebControls.Button ButtonCE;
		
		protected System.Web.UI.WebControls.Button ButtonEquals;
	}
}
